### ISSUE TITLE
Array 'mp_matching_rhs_record_weight' might be empty - leads to segfault

### ISSUE THREAD

**Issue by stoianmihail** [InitialDLab/SampleJoin#2]
Hi!

I get a segfault at this line: https://github.com/InitialDLab/SampleJoin/blob/454474287edecfbbb0fc0657e1cfebc59854dc7b/mmJoin/src/database/jefastVertex.h#L269 because `mp_matching_rhs_record_weight` is empty at that point in time, while `m_matching_rhs_record_ids` has 3 elements (I have a dataset with 4 small tables - 2-3 rows each). How can I find a fix quick? Or should it be the case that both arrays have the same number of elements?

Thanks for your time!

**Comment by zzy7896321** [comment]
Hi Stoian,

Did that happen with the last table in the join? For the last table in a chain join or any leaf table in a general acyclic join, mp_matching_rhs_record_weight is always empty because the weight defaults to 1. The sort() function wasn't supposed to be called on the last table/leaf table.

If it's not the last table/leaf table, would you mind sending a snippet of your query specification code?

Zhuoyue
